server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health"

spring:
  # Details for our datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "pass"
  # Hibernate
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      # DO NO DROP-CREATE SCHEMA
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0