# Run with
# docker-compose -p stock-market-data -f .\docker\docker-compose.yml up -d

networks:
  market:

services:
  my-market-viewer:
    networks:
      - market
    image: my-market-viewer:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # expose the ports to connect from outside docker env
    ports:
      # outside:inside
      - 3000:8080
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      JAVA_TOOL_OPTIONS: '-Dspring.datasource.url=jdbc:postgresql://postgres:5432/postgres'