# Use postgres/example user/password credentials

# Run with 
# docker-compose -p stock-market-data -f .\database\docker-compose.yml up -d

networks:
  market:

# Generic credentials to start
services:
  postgres:
    networks:
      - market
    container_name: postgres
    image: postgres:18.3-alpine3.23@sha256:c5739fc99d1a3278c0a2113758a2433ce29ef964b30df705094fd77dfa5da2fa
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # expose the ports to connect from outside docker env
    ports:
      - 5432:5432
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # default user/pass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  adminer:
    networks:
      - market
    image: adminer
    restart: always
    ports:
      - 8081:8080
